/* WEB UI EXTENSION MAP: add tutorial commands in ACTION_GROUPS and status cards in renderState(). */
"use strict";

const BLE_SERVICE_UUID="6e400001-b5a3-f393-e0a9-e50e24dcca9e",BLE_RX_UUID="6e400002-b5a3-f393-e0a9-e50e24dcca9e",BLE_TX_UUID="6e400003-b5a3-f393-e0a9-e50e24dcca9e",BLE_CHUNK=20;
const API_BASE=String(window.ESP32_API_BASE||"").replace(/\/+$/,""),enc=new TextEncoder(),dec=new TextDecoder(),elements={};
for(const id of ["buildVersion","liveDot","liveText","connectBle","disconnectBle","transportSummary","compiledSummary","commandPreset","commandInput","sendCommands","stopAll","clearLog","log","statusSummary","statusGrid","selfTestSummary","otaFile","otaUpload","otaProgress","otaMessage"])elements[id]=document.getElementById(id);

const state={transport:"http",latest:null,cursor:null,lastContact:0,busy:false,otaActive:false,bleDevice:null,bleRx:null,bleTx:null,bleBuffer:"",bleStatePending:false,bleStateAt:0,httpQuietUntil:0,nextStateAt:0,retryAt:0,httpFailures:0,httpTail:Promise.resolve(),dacHolds:new Map()};
const ACTION_GROUPS=[
  ["Core",[["Ping","Ping"],["Status","Status"],["Read config","ConfigRead"],["Help","Help"],["Indicators","IndicatorTest"]]],
  ["Send / bridge",[["Send","Send:hello from controller"],["Send to BLE","SendBLE:hello from Wi-Fi","ble-output"],["Send Wi-Fi","SendWiFi:hello from BLE","wifi-output"],["Send USB","SendSerial:hello from controller"],["Send status","SendStatus"]]],
  ["Stepper addon",[["360° CW","DEG:10,360,1","addon"],["360° CCW","DEG:10,360,2","addon"],["Fast test","FastWiperTest","addon"],["Coils off","CoilsOff","addon"],["Motor status","GetMotorStats","addon"]]],
  ["Radio profiles",[["Wi-Fi","ModeWiFi","wifi",1],["Wi-Fi + BLE","ModeWiFiBLE","wifi+ble",1],["Wi-Fi + BLE P","ModeWiFiBLEP","wifi+ble",1],["BLE only","ModeBLE","ble",1],["BT serial","ModeBTSerial","spp",1],["USB only","ModeUSB",null,1],["Radio status","RadioStatus"]]],
  ["Self-test",[["Start sweep","SelfTestStart",null,1],["Print status","SelfTestStatus"],["Abort","SelfTestAbort",null,1],["Clear report","SelfTestClear"]]],
  ["Debug",[["Debug boot tests","DebugMode"],["Production boot","ProductionMode"],["Load saved config","ConfigLoad"],["Clear STA","WiFiStaClear","wifi",1]]]
];

function api(path){return API_BASE+path}function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}function now(){return new Date().toLocaleTimeString()}function usingBle(){return state.transport==="ble"&&state.bleRx&&state.bleTx}
function setLive(ok,text){elements.liveDot.classList.toggle("on",ok);elements.liveText.textContent=text}
function redact(line){return /^(WiFi(?:Ap|Sta)Password:)/i.test(line)?line.split(":",1)[0]+":<redacted>":line}
function appendLog(line){elements.log.textContent+=line+"\n";if(elements.log.textContent.length>32000)elements.log.textContent=elements.log.textContent.slice(-24000);elements.log.scrollTop=elements.log.scrollHeight}function log(message,level="info"){appendLog(`[${now()}] ${level.toUpperCase()} ${message}`)}function rawLog(message){appendLog(String(message))}
function rid(){return `web-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`}
async function fetchTimed(url,options={},ms=4200){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
async function readJson(response,label){const text=await response.text();if(!response.ok)throw new Error(`${label} HTTP ${response.status}${text?`: ${text.slice(0,100)}`:""}`);try{return JSON.parse(text)}catch(error){throw new Error(`${label} invalid JSON (${text.length} bytes)`)}}
function down(error){const message=error?.name==="AbortError"?"HTTP timeout":error?.message||String(error),wasLive=elements.liveDot.classList.contains("on");setLive(false,message);if(wasLive)log(message,"error")}
async function pingHttp(){const response=await fetchTimed(api("/api/ping"),{cache:"no-store"},2200);await readJson(response,"Ping");state.lastContact=Date.now()}
function compiled(requirement){const radio=state.latest?.radio||{},send=state.latest?.send||{};if(!requirement)return true;if(requirement==="addon")return state.latest?.addon?.active!==false;if(requirement==="wifi")return radio.wifiCompiled!==false;if(requirement==="wifi-output")return send.wifi===true;if(requirement==="ble")return radio.bleCompiled!==false;if(requirement==="ble-output")return send.ble===true;if(requirement==="spp")return radio.sppCompiled!==false;return radio.wifiCompiled!==false&&radio.bleCompiled!==false}
function buildCommandMenu(){for(const [group,items] of ACTION_GROUPS){const optgroup=document.createElement("optgroup");optgroup.label=group;for(const [label,command,requires,confirm] of items){const option=document.createElement("option");option.value=command;option.textContent=label+" · "+command;if(requires)option.dataset.requires=requires;if(confirm)option.dataset.confirm="1";optgroup.append(option)}elements.commandPreset.append(optgroup)}}
function updateActions(){for(const item of document.querySelectorAll("[data-command],[data-hold-on],option[data-requires]"))item.disabled=state.busy||!compiled(item.dataset.requires);if(elements.commandPreset.selectedOptions[0]?.disabled)elements.commandPreset.selectedIndex=0}
function renderTransport(){const ble=usingBle();elements.transportSummary.textContent=ble?"BLE transport":"Wi-Fi transport";elements.connectBle.disabled=state.busy||ble||!navigator.bluetooth||state.latest?.radio?.bleCompiled===false;elements.disconnectBle.disabled=state.busy||!ble;elements.otaUpload.disabled=state.busy||state.otaActive;elements.sendCommands.disabled=state.busy;updateActions()}
function card(label,value){return `<div class="status"><span>${label}</span><strong>${value}</strong></div>`}
function renderState(data){state.latest=data;state.lastContact=Date.now();if(state.cursor===null)state.cursor=Number(data.latestEventId)||0;const radio=data.radio||{},send=data.send||{},motor=data.motor||{},channels=data.dac?.channels||[],queue=data.queue||{},test=data.selfTest||{};const wifi=radio.wifiCompiled===false?"not compiled":`${radio.wifiState||"off"} ${radio.ip||""}`.trim(),ble=radio.bleCompiled===false?"not compiled":send.ble?"connected + TX":send.bleConnected?"connected, notifications off":radio.bleRunning?"advertising":"off",spp=radio.sppCompiled===false?"not compiled":radio.sppConnected?"connected":radio.sppRunning?"running":"off",addon=data.addon?.name||"none",motorText=data.addon?.active===false?"not loaded":motor.moving?`${motor.currentRpm} RPM, ${motor.remainingSteps} steps`:motor.testActive?"test active":"idle",dac=index=>{const channel=channels[index-1]||{};return data.addon?.active===false?"not loaded":channel.enabled?`${channel.outputMv||0} mV${channel.oneShot?" test":""}`:"off"},profile=radio.bootModeActive||data.bootMode||"?";elements.statusGrid.innerHTML=[card("Boot",profile),card("Addon",addon),card("Wi-Fi",wifi),card("BLE",ble),card("SPP",spp),card("Motor",motorText),card("DAC 1",dac(1)),card("DAC 2",dac(2)),card("Queue",`${queue.waiting??0}/${queue.capacity??0}`),card("Heap",`${data.freeHeap??0} B free · ${data.largestHeapBlock??0} B largest`),card("Self-test",test.active?`${test.current||0}/${test.total||0}`:test.phase||"idle")].join("");elements.statusSummary.textContent=`${profile} · ${addon} · Wi-Fi ${wifi} · BLE ${ble}`;elements.buildVersion.textContent=`${data.firmware||"ESP32 controller"} · ${data.version||"unknown build"}`;elements.compiledSummary.textContent=`Compiled: Wi-Fi ${radio.wifiCompiled===false?"off":"on"}, BLE ${radio.bleCompiled===false?"off":"on"}, SPP ${radio.sppCompiled===false?"off":"on"}`;elements.selfTestSummary.textContent=`${test.phase||"Idle"}: ${test.current||0}/${test.total||0}, pass ${test.pass||0}, fail ${test.fail||0}, skip ${test.skip||0}, boots ${test.boots||0}. ${test.lastResult||"No run recorded."}`;setLive(true,usingBle()?"BLE connected":"HTTP connected");renderTransport()}
async function postHttpNow(body,id,fast){const clean=String(body||"").replace(/\r/g,"").trim();if(!clean)throw new Error("Empty command");let last;const timeout=fast?2200:6500,delays=fast?[0]:[0,180,500];state.httpQuietUntil=Date.now()+timeout+300;for(const delay of delays){if(delay)await sleep(delay);try{const response=await fetchTimed(api("/api/command"),{method:"POST",headers:{"Content-Type":"application/octet-stream","Accept":"application/json","X-Request-ID":id},body:clean,keepalive:fast},timeout),payload=await readJson(response,"Command");state.lastContact=Date.now();if(payload.accepted){state.cursor=Math.max(state.cursor??0,Number(payload.latestEventId)||0);state.httpQuietUntil=Date.now()+100;setLive(true,"HTTP connected");return payload}last=new Error(payload.error||`Command HTTP ${response.status}`);if(!(response.status===429||response.status===503||payload.retryable))break}catch(error){last=error}}state.httpQuietUntil=Date.now()+100;throw last||new Error("Command failed")}
function postHttp(body,id=rid(),fast=false){const run=()=>postHttpNow(body,id,fast),pending=state.httpTail.then(run,run);state.httpTail=pending.catch(()=>{});return pending}
async function writeBle(text){if(!usingBle())throw new Error("BLE disconnected");const bytes=enc.encode(text);for(let index=0;index<bytes.length;index+=BLE_CHUNK){const chunk=bytes.slice(index,index+BLE_CHUNK);if(state.bleRx.writeValueWithoutResponse)await state.bleRx.writeValueWithoutResponse(chunk);else await state.bleRx.writeValue(chunk);await sleep(14)}}
async function runCommand(body,fast=false){const clean=String(body||"").trim();if(!clean)throw new Error("Empty command");log(`TX ${usingBle()?"BLE":"HTTP"} ${clean.split("\n").map(redact).join(" | ")}`,"send");if(usingBle()){await writeBle(clean+"\n");return}const result=await postHttp(clean,rid(),fast);log(`HTTP accepted ${result.acceptedLines||1} line${result.acceptedLines===1?"":"s"}`,"status");return result}
function handleBleLine(line){if(!line)return;state.lastContact=Date.now();if(line.startsWith("@STATE ")){state.bleStatePending=false;state.bleStateAt=0;try{renderState(JSON.parse(line.slice(7)))}catch(error){log(`BLE state parse: ${error.message}`,"error")}return}const match=line.match(/^\[(\d+)\]\[([^\]]+)\]\[([^\]]+)\](?:\[([^\]]+)\])?\s*(.*)$/);if(match){state.cursor=Math.max(state.cursor??0,Number(match[1])||0);log(`${match[3]}${match[4]?` #${match[4]}`:""}: ${match[5]}`,match[2].toLowerCase());return}line.startsWith("@ERROR")?log(line,"error"):rawLog(line)}
function handleBleData(event){state.bleBuffer+=dec.decode(event.target.value,{stream:true});let at;while((at=state.bleBuffer.indexOf("\n"))>=0){handleBleLine(state.bleBuffer.slice(0,at).replace(/\r$/,"").trim());state.bleBuffer=state.bleBuffer.slice(at+1)}}
function bleDisconnected(){const wasBle=state.transport==="ble"||state.bleRx||state.bleTx;state.transport="http";state.bleRx=null;state.bleTx=null;state.bleBuffer="";state.nextStateAt=0;setLive(false,"BLE disconnected");renderTransport();if(wasBle)log("BLE disconnected; Wi-Fi resumed","warning")}
async function connectBle(){if(!navigator.bluetooth)throw new Error("Web Bluetooth is unavailable");const arm=Date.now()-state.lastContact<7000?postHttp("BLEWebHandoff","ble-arm-"+Date.now()).catch(()=>{}):Promise.resolve(),devicePromise=navigator.bluetooth.requestDevice({filters:[{services:[BLE_SERVICE_UUID]}],optionalServices:[BLE_SERVICE_UUID]}),[,device]=await Promise.all([arm,devicePromise]);device.addEventListener("gattserverdisconnected",bleDisconnected);const server=await device.gatt.connect(),service=await server.getPrimaryService(BLE_SERVICE_UUID);state.bleRx=await service.getCharacteristic(BLE_RX_UUID);state.bleTx=await service.getCharacteristic(BLE_TX_UUID);await state.bleTx.startNotifications();state.bleTx.addEventListener("characteristicvaluechanged",handleBleData);state.bleDevice=device;state.transport="ble";state.bleBuffer="";renderTransport();setLive(true,"BLE connected");log(`BLE connected to ${device.name||"ESP32"}`,"status");await writeBle("@STATE\n")}
function disconnectBle(){if(state.bleDevice?.gatt?.connected)state.bleDevice.gatt.disconnect();else bleDisconnected()}
function coexHttpMode(){const m=state.latest?.radio?.bootModeActive;return m==="WIFI_BLE"||m==="WIFI_BLE_P"}
function showEvent(event){const text=event.t||"",level=event.l||"info";if(event.q){rawLog(text);return}const source=event.s||"Internal",requestId=event.r||"";log(`${source}${requestId?` #${requestId}`:""}: ${text}`,String(level).toLowerCase())}
async function pollHttpOnce(){const time=Date.now();if(state.busy||state.otaActive||time<state.httpQuietUntil)return 100;if(time<state.retryAt)return Math.min(350,state.retryAt-time);const getState=!state.latest||time>=state.nextStateAt;try{if(getState){const response=await fetchTimed(api("/api/state"),{cache:"no-store"},coexHttpMode()?4800:3200);renderState(await readJson(response,"State"));state.nextStateAt=Date.now()+1500}else{const response=await fetchTimed(api(`/api/events?since=${state.cursor??0}&limit=4`),{cache:"no-store"},coexHttpMode()?4200:2800),payload=await readJson(response,"Events");state.lastContact=Date.now();if(payload.gap)log("Event history wrapped","warning");for(const event of payload.events||[])showEvent(event);state.cursor=Math.max(state.cursor??0,Number(payload.cursor)||0);setLive(true,"HTTP connected");state.httpFailures=0;state.retryAt=0;return payload.more?120:500}state.httpFailures=0;state.retryAt=0;return 350}catch(error){state.httpFailures++;if(state.httpFailures<2)return 250;try{await pingHttp();setLive(true,"HTTP connected · API retrying");state.retryAt=Date.now()+(state.httpFailures<4?700:2200);return 300}catch(pingError){down(pingError);state.retryAt=Date.now()+3000;return 1000}}}
async function pollLoop(){if(state.otaActive){setTimeout(pollLoop,250);return}if(usingBle()){if(state.bleStatePending&&Date.now()-state.bleStateAt>4000)state.bleStatePending=false;if(!state.bleStatePending){state.bleStatePending=true;state.bleStateAt=Date.now();writeBle("@STATE\n").catch(error=>{state.bleStatePending=false;state.bleStateAt=0;log(error.message,"error")})}setTimeout(pollLoop,900);return}setTimeout(pollLoop,await pollHttpOnce())}
async function withLock(work){if(state.busy)return;state.busy=true;renderTransport();try{await work()}catch(error){log(error.message||String(error),"error")}finally{state.busy=false;renderTransport()}}
async function prepareHttpForOta(){if(!usingBle())return;elements.otaMessage.textContent="Stopping outputs and handing OTA from BLE to Wi-Fi...";await writeBle("StopAll\n");await sleep(180);disconnectBle();for(let attempt=0;attempt<8&&usingBle();attempt++)await sleep(100);if(usingBle())bleDisconnected();let last;for(let attempt=0;attempt<6;attempt++){try{await pingHttp();log("OTA control handed from BLE to Wi-Fi","status");return}catch(error){last=error;await sleep(500)}}throw new Error(`Wi-Fi OTA endpoint is unavailable after BLE handoff${last?.message?`: ${last.message}`:""}`)}
async function uploadFirmware(){const file=elements.otaFile.files?.[0];if(!file)throw new Error("Choose an application .bin first");if(!file.name.toLowerCase().endsWith(".bin"))throw new Error("Choose an ESP32 application .bin file");if(file.size<1024)throw new Error("Firmware image is too small to be a valid ESP32 application");const magic=new Uint8Array(await file.slice(0,1).arrayBuffer())[0];if(magic!==0xe9)throw new Error("Selected file does not have an ESP32 application image header");state.otaActive=true;renderTransport();elements.otaProgress.value=0;elements.otaMessage.textContent="Preparing OTA...";try{await prepareHttpForOta();elements.otaMessage.textContent="Uploading over Wi-Fi...";const form=new FormData();form.append("firmware",file,file.name);await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST",api("/api/ota"));xhr.timeout=180000;xhr.setRequestHeader("X-Request-ID",rid());xhr.setRequestHeader("X-Firmware-Size",String(file.size));xhr.upload.onprogress=event=>{if(event.lengthComputable){const progress=Math.min(99,Math.round(event.loaded/event.total*100));elements.otaProgress.value=progress;elements.otaMessage.textContent=`Uploading ${progress}% over Wi-Fi`}};xhr.onerror=()=>reject(new Error("OTA upload connection failed"));xhr.ontimeout=()=>reject(new Error("OTA upload timed out"));xhr.onabort=()=>reject(new Error("OTA upload was aborted"));xhr.onload=()=>{let payload={};try{payload=JSON.parse(xhr.responseText||"{}")}catch(error){}if(xhr.status>=200&&xhr.status<300&&payload.ok)resolve(payload);else reject(new Error(payload.error||`OTA HTTP ${xhr.status}`))};xhr.send(form)});elements.otaProgress.value=100;elements.otaMessage.textContent="Image validated. Controller is rebooting.";state.httpQuietUntil=Date.now()+10000;log("OTA image validated; reboot scheduled","status")}finally{state.otaActive=false;renderTransport()}}
function selectedOption(){const option=elements.commandPreset.selectedOptions[0];return option&&option.value===elements.commandInput.value.trim()?option:null}
function sendInput(){const option=selectedOption(),command=elements.commandInput.value;if(option?.dataset.confirm&&!window.confirm(`Send ${command}?\n\nUSB serial remains the recovery path.`))return;withLock(()=>runCommand(command))}
function holdVisual(button,on){button.classList.toggle("active",on);button.setAttribute("aria-pressed",on)}
function startDacHold(button,event){if(button.disabled||state.dacHolds.has(button))return;event.preventDefault();button.setPointerCapture?.(event.pointerId);holdVisual(button,true);state.dacHolds.set(button,runCommand(button.dataset.holdOn,true).catch(error=>log(error.message||String(error),"error")))}
function releaseDacHold(button){const start=state.dacHolds.get(button);if(!start)return;state.dacHolds.delete(button);holdVisual(button,false);Promise.resolve(start).finally(()=>runCommand(button.dataset.holdOff,true).catch(error=>log(error.message||String(error),"error")))}
function releaseAllDacs(){for(const button of [...state.dacHolds.keys()])releaseDacHold(button)}

document.addEventListener("click",event=>{const button=event.target.closest("button[data-command]");if(!button)return;const command=button.dataset.command;if(button.dataset.confirm&&!window.confirm(`Send ${command}?\n\nUSB serial remains the recovery path.`))return;withLock(()=>runCommand(command))});
elements.commandPreset.addEventListener("change",()=>{const option=elements.commandPreset.selectedOptions[0];if(option?.value){elements.commandInput.value=option.value;elements.commandInput.focus()}});
elements.commandInput.addEventListener("input",()=>{if(elements.commandPreset.value!==elements.commandInput.value.trim())elements.commandPreset.selectedIndex=0});
elements.commandInput.addEventListener("keydown",event=>{if(event.ctrlKey&&event.key==="Enter"){event.preventDefault();sendInput()}});
elements.sendCommands.addEventListener("click",sendInput);elements.stopAll.addEventListener("click",()=>{releaseAllDacs();runCommand("StopAll").catch(error=>log(error.message,"error"))});elements.connectBle.addEventListener("click",()=>withLock(connectBle));elements.disconnectBle.addEventListener("click",disconnectBle);elements.clearLog.addEventListener("click",()=>elements.log.textContent="");elements.otaUpload.addEventListener("click",()=>withLock(uploadFirmware));
for(const button of document.querySelectorAll("[data-hold-on]")){button.addEventListener("pointerdown",event=>startDacHold(button,event));button.addEventListener("lostpointercapture",()=>releaseDacHold(button))}for(const type of ["pointerup","pointercancel"])document.addEventListener(type,releaseAllDacs);window.addEventListener("blur",releaseAllDacs);window.addEventListener("pagehide",releaseAllDacs);document.addEventListener("visibilitychange",()=>document.hidden&&releaseAllDacs());

buildCommandMenu();renderTransport();log("OK","status");pollLoop();
